"""
ORION Agent Interface Definitions

Re-exports all base abstractions, data models, and agent interfaces
for easy imports across the system.
"""

from .base import (
    AgentExecutionError,
    AgentExecutionResult,
    AgentMessage,
    AgentProvider,
    AgentStatus,
    AgentValidationError,
    AnomalyRecord,
    BaseAgent,
    EvidenceItem,
    Severity,
    TimeRange,
)
from .supervisor import (
    InvestigationConfig,
    InvestigationStatus,
    InvestigationStep,
    Recommendation,
    RootCauseHypothesis,
    SupervisorAgent,
    SupervisorInput,
    SupervisorOutput,
)
from .data_analysis import (
    Correlation,
    DataAnalysisAgent,
    DataAnalysisInput,
    DataAnalysisOutput,
    DataQualityReport,
    DimensionAnalysis,
    MetricSummary,
    NotableChange,
    StatisticalTest,
    TrendAnalysis,
)
from .anomaly_investigation import (
    AnomalyClassification,
    AnomalyInvestigationAgent,
    AnomalyInvestigationInput,
    AnomalyInvestigationOutput,
    CorrelationNarrative,
    Finding,
    OnsetAnalysis,
    PatternAnalysis,
    PropagationStep,
    TemporalPattern,
)
from .root_cause import (
    CausalStep,
    EvidenceStrengthReport,
    RootCauseAgent,
    RootCauseHypothesis as RootCauseDetailHypothesis,
    RootCauseInput,
    RootCauseOutput,
)
from .business_impact import (
    BusinessImpactAgent,
    BusinessImpactInput,
    BusinessImpactOutput,
    DimensionImpact,
    ProjectedImpact,
    RealizedImpact,
    SeverityAssessment,
)
from .recommendation import (
    ExpectedImpact,
    ImplementationDetails,
    Recommendation as RecommendationDetail,
    RecommendationAgent,
    RecommendationInput,
    RecommendationOutput,
)
from .action import (
    ActionAgent,
    ActionInput,
    ActionOutput,
    ActionResult,
    ActionStatus,
    ActionType,
    AuditLogEntry,
)

__all__ = [
    # Base
    "AgentExecutionError",
    "AgentExecutionResult",
    "AgentMessage",
    "AgentProvider",
    "AgentStatus",
    "AgentValidationError",
    "AnomalyRecord",
    "BaseAgent",
    "EvidenceItem",
    "Severity",
    "TimeRange",
    # Agents
    "SupervisorAgent",
    "SupervisorInput",
    "SupervisorOutput",
    "InvestigationConfig",
    "InvestigationStatus",
    "InvestigationStep",
    "DataAnalysisAgent",
    "DataAnalysisInput",
    "DataAnalysisOutput",
    "DimensionAnalysis",
    "MetricSummary",
    "TrendAnalysis",
    "StatisticalTest",
    "NotableChange",
    "Correlation",
    "DataQualityReport",
    "AnomalyInvestigationAgent",
    "AnomalyInvestigationInput",
    "AnomalyInvestigationOutput",
    "PatternAnalysis",
    "TemporalPattern",
    "CorrelationNarrative",
    "PropagationStep",
    "OnsetAnalysis",
    "AnomalyClassification",
    "Finding",
    "RootCauseAgent",
    "RootCauseInput",
    "RootCauseOutput",
    "RootCauseHypothesis",
    "RootCauseDetailHypothesis",
    "CausalStep",
    "EvidenceStrengthReport",
    "BusinessImpactAgent",
    "BusinessImpactInput",
    "BusinessImpactOutput",
    "RealizedImpact",
    "ProjectedImpact",
    "DimensionImpact",
    "SeverityAssessment",
    "RecommendationAgent",
    "RecommendationInput",
    "RecommendationOutput",
    "Recommendation",
    "RecommendationDetail",
    "ExpectedImpact",
    "ImplementationDetails",
    "ActionAgent",
    "ActionInput",
    "ActionOutput",
    "ActionResult",
    "ActionStatus",
    "ActionType",
    "AuditLogEntry",
]
