"""
ActionAgent Interface

Executes approved actions. Each action type has a registered handler.
The ActionAgent validates preconditions, executes the action, and
reports results.

CRITICAL: ActionAgent ONLY executes actions that have been explicitly
approved by a human through the approval workflow. It checks for a
valid approval_id before any execution.
"""

from enum import Enum
from typing import Any, Type

from pydantic import BaseModel, Field

from .base import BaseAgent


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ActionStatus(str, Enum):
    """Status of an action execution."""
    PENDING = "pending"
    VALIDATING = "validating"
    EXECUTING = "executing"
    SUCCESS = "success"
    PARTIAL = "partial"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


class ActionType(str, Enum):
    """Available action types in v1."""
    ADJUST_SUPPORT_STAFFING = "adjust_support_staffing"
    TRIGGER_INVENTORY_REORDER = "trigger_inventory_reorder"
    ADJUST_MARKETING_BUDGET = "adjust_marketing_budget"
    CREATE_RETENTION_CAMPAIGN = "create_retention_campaign"
    ESCALATE_TO_MANAGEMENT = "escalate_to_management"


# ---------------------------------------------------------------------------
# Output Sub-Schemas
# ---------------------------------------------------------------------------

class ActionResult(BaseModel):
    """Result of an action execution."""
    changes_made: list[str]
    metrics_affected: list[str]
    rollback_available: bool
    rollback_instructions: str | None = None


class AuditLogEntry(BaseModel):
    """Audit log entry generated by the action."""
    entity_type: str = "action"
    entity_id: str
    action: str
    actor: str
    details: dict[str, Any]
    timestamp: str


# ---------------------------------------------------------------------------
# Input / Output Schemas
# ---------------------------------------------------------------------------

class ActionInput(BaseModel):
    """Input to the ActionAgent."""
    action_id: str
    action_type: ActionType
    parameters: dict[str, Any]
    approval_id: str = Field(
        ..., description="Must reference a valid, active approval"
    )
    investigation_id: str


class ActionOutput(BaseModel):
    """Output from the ActionAgent."""
    execution_id: str
    action_id: str
    status: ActionStatus
    result: ActionResult | None = None
    error: str | None = None
    audit_entry: AuditLogEntry


# ---------------------------------------------------------------------------
# Agent Interface
# ---------------------------------------------------------------------------

class ActionAgent(BaseAgent):
    """
    Executes approved actions through registered handlers.

    Every execution:
    1. Validates approval_id is genuine and active
    2. Validates preconditions for the action
    3. Executes the action through the appropriate handler
    4. Records the result in the audit trail
    5. Returns structured execution results
    """

    @property
    def name(self) -> str:
        return "action_agent"

    @property
    def description(self) -> str:
        return (
            "Executes human-approved actions through registered handlers, "
            "with precondition validation and full audit logging."
        )

    @property
    def input_schema(self) -> Type[BaseModel]:
        return ActionInput

    @property
    def output_schema(self) -> Type[BaseModel]:
        return ActionOutput

    @property
    def tools(self) -> list[str]:
        return [
            "execute_support_action",
            "execute_inventory_action",
            "execute_marketing_action",
            "log_audit_entry",
        ]

    async def execute(self, input_data: ActionInput) -> ActionOutput:
        raise NotImplementedError("Implement in concrete provider class")

    async def validate_output(self, output: ActionOutput) -> bool:
        if not output.audit_entry:
            return False  # Every action must produce an audit entry
        if output.status == ActionStatus.SUCCESS and not output.result:
            return False  # Successful actions must have a result
        return True
